name: cfdna_wgs
channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconductor-genomeinfodb
  - bioconductor-genomicranges
  - bioconductor-hmmcopy
  - hmmcopy
  - r-argparse
  - r-optparse
  - samtools
  - snakemake
