# [[file:~/repos/cfdna-wgs/cfdna-wgs.org::*%5B%5Bfile:config/int_test.yaml%5D%5BSnakemake%20configuration%20YAML%5D%5D][[[file:config/int_test.yaml][Snakemake configuration YAML]]:1]]
##############################
###   Configuration Yaml   ###
##############################

###   Parameters Intended To Be Common Across Workflows    ###

blklist: "/mnt/ris/szymanski/Active/test/inputs/hg38-blacklist.v2.bed.gz"
data_dir: "/mnt/ris/szymanski/Active/test"
genome_fasta: "/mnt/ris/szymanski/Active/test/inputs/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
threads: 4

###   Unique properties from this repo   ###

frag_repo: "/home/jszymanski/repos/cfdna-wgs"

frag_distro: "90_150"

gc5mb: "test/inputs/gc5mb.bed"
# [[file:config/int_test.yaml][Snakemake configuration YAML]]:1 ends here
